### ISSUE TITLE
ERROR: SID Cookie is empty

### ISSUE THREAD

**Issue by 66Bunz** [AlexKhomych/qbittorrent_exporter#3]
I cannot make the exporter connect to qbittorrent, because I get an error about the SID Cookie

These are the logs of the exporter

```log
time=2025-06-20T09:13:35.901Z level=INFO msg="Updated logger with LogFormat: default, LogLevel: info"

time=2025-06-20T09:13:35.902Z level=ERROR msg="SID Cookie is empty"

time=2025-06-20T09:13:35.902Z level=ERROR msg="Failed to login"
```

I tried to manually connect with curl
```curl
curl -i -X POST http://192.168.1.101:8080/api/v2/auth/login --data "username=admin&password=adminadmin"
```

and I get a valid response:

```log
HTTP/1.1 200 OK
connection: keep-alive
content-length: 3
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-src 'self' blob:; frame-ancestors 'self';
content-type: text/plain; charset=UTF-8
cross-origin-opener-policy: same-origin
date: Fri, 20 Jun 2025 09:07:43 GMT
referrer-policy: same-origin
set-cookie: SID=redacted; HttpOnly; SameSite=Strict; path=/
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```

This is my compose for the exporter:

```yaml
qbittorrent_exporter:
    image: alexkhomychw/qbittorrent_exporter:1.0.0
    container_name: qbittorrent_exporter
    ports:
      - "17171:17171"
    environment:
      QBE_URL: "http://192.168.1.101:8080"
      QBE_USERNAME: "admin"
      QBE_PASSWORD: "adminadmin"
    restart: unless-stopped
```

I don't know if I'm missing something or not

**Comment by AlexKhomych** [comment]
Good day 🙂,

I've tried to recreate environment similar to what you have provided using docker compose file.
```yml
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.4
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      monitoring:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

  qbittorrent_exporter:
    image: alexkhomychw/qbittorrent_exporter:1.0.0
    container_name: qbittorrent_exporter
    ports:
      - "17171:17171"
    networks:
      monitoring:
        ipv4_address: 172.20.0.3
    environment:
      QBE_URL: "http://172.20.0.2:8080"
      QBE_USERNAME: "admin"
      QBE_PASSWORD: "adminadmin"
    restart: unless-stopped
    depends_on:
      - qbittorrent

volumes:
  qbittorrent-config:
    name: qbittorrent-config

networks:
  monitoring:
    name: monitoring
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
```

From information that you provided, credentials seem correct. And the error message "SID Cookie is empty" is only present when credentials are wrong.

That is when I thought about inability to log in that have happened to me in the past. One of possible issues that I have seen people have is by providing wrong credentials, they get blocked by qBittorrent WebUI.

In my case, running qBittorrent in docker. Following steps have been performed to verify it:
1) Execute into qBittorrent container.
```bash
docker exec -it qbittorrent /bin/bash
```
2) View qBittorrent logs.
```bash
tail /config/qBittorrent/logs/qbittorrent.log
```
3) The following lines can be observed.
```
(W) 2025-06-20T14:09:28 - WebAPI login failure. Reason: IP has been banned, IP: ::ffff:172.20.0.3, username: admin
(W) 2025-06-20T14:09:54 - WebAPI login failure. Reason: IP has been banned, IP: ::ffff:172.20.0.3, username: admin
(W) 2025-06-20T14:10:46 - WebAPI login failure. Reason: IP has been banned, IP: ::ffff:172.20.0.3, username: admin
(W) 2025-06-20T14:11:46 - WebAPI login failure. Reason: IP has been banned, IP: ::ffff:172.20.0.3, username: admin
```

If that is the case, then try to restart qBittorrent, to clear the ban list.
By navigating via `Tools -> Options -> WebUI -> Authentication` on the webpage.
For future you can play around with `Bypass authentication for clients in whitelisted IP subnets`, 'Ban client after consecutive failures` and `ban for`. Although if your qBittorrent is accessible outside of local network or others than you, it might be better to not change `ban for` time and amount of `consecutive failures`.
